In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('PlayersU18.csv')
df1 = pd.read_csv('U18_minutes.csv')

In [4]:
df

,Unnamed: 0,season,rank,player,team,games,index,average,per_40min
0,0,2020-21 VALENCIA,1,"SOCHAN, JEREMY",U18 ratiopharm Ulm,4,90,22.50,29.02
1,1,2020-21 VALENCIA,2,"CAICEDO, MICHAEL",U18 FC Barcelona,4,78,19.50,28.29
2,2,2020-21 VALENCIA,3,"VILLAR, RAFA",U18 FC Barcelona,4,76,19.00,34.18
3,3,2020-21 VALENCIA,4,"LOEMBA, MARC-ANTOINE",U18 Nanterre 92,4,67,16.75,22.03
4,4,2020-21 VALENCIA,5,"RAYNAUD, MAXIME",U18 Nanterre 92,4,65,16.25,18.83
...,...,...,...,...,...,...,...,...,...
5660,5660,2002-03,89,"GIANNAKIS, DIMITRIS",U18 AEK ATHENS,3,-7,-2.33,-7.57
5661,5661,2002-03,90,"STRASEVICIUS, SARUNAS",U18 ZALGIRIS KAUNAS,3,-8,-2.67,-10.67
5662,5662,2002-03,90,"MUBARAK, MOSES",U18 ELAN BEARNAIS PAU ORTHEZ,3,-8,-2.67,-9.14
5663,5663,2002-03,92,"MAXIMOV, SERGIOS",U18 AEK ATHENS,3,-10,-3.33,-8.16
5664,5664,2002-03,93,"KULENOVIC, EMIR",U18 UNION OLIMPIJA LJUBLJANA,3,-11,-3.67,-9.57

In [5]:
playersIndex = df.drop('Unnamed: 0', axis=1)

In [6]:
playersIndex.columns = playersIndex.columns.str.strip()

In [7]:
playersMinutes = df1.drop('Unnamed: 0', axis=1)

In [8]:
playersMinutes.columns = playersMinutes.columns.str.strip()

In [9]:
playersMinutes

,season,rank,player,team,games,minutes
0,2020-21 VALENCIA,1,"KASIAMA, KENNY",U18 LDLC ASVEL Villeurbanne,4,138:57
1,2020-21 VALENCIA,2,"RAYNAUD, MAXIME",U18 Nanterre 92,4,138:04
2,2020-21 VALENCIA,3,"HOUINSOU, KYMANY",U18 LDLC ASVEL Villeurbanne,4,136:08
3,2020-21 VALENCIA,4,"SOCHAN, JEREMY",U18 ratiopharm Ulm,4,124:02
4,2020-21 VALENCIA,5,"LOEMBA, MARC-ANTOINE",U18 Nanterre 92,4,121:38
...,...,...,...,...,...,...
5660,2002-03,89,"PSIRIS, SOTIRIOS",U18 AEK ATHENS,2,4:00
5661,2002-03,90,"DRITSOS, GEORGIOS",U18 AEK ATHENS,1,2:00
5662,2002-03,90,"KIRIAKIDIS, SAVAS",U18 AEK ATHENS,1,2:00
5663,2002-03,90,"KORKIDIS, EVANGELOS",U18 AEK ATHENS,1,2:00
5664,2002-03,93,"SHIFER, YEHONATAN",U18 MACCABI TEL AVIV,1,1:00

In [10]:
baseU18 = playersIndex.merge(playersMinutes[['season', 'player', 'team', 'games', 'minutes']],'left',on=['season', 'player', 'team', 'games'],suffixes=('', 'minutes'))

In [11]:
baseU18

,season,rank,player,team,games,index,average,per_40min,minutes
0,2020-21 VALENCIA,1,"SOCHAN, JEREMY",U18 ratiopharm Ulm,4,90,22.50,29.02,124:02
1,2020-21 VALENCIA,2,"CAICEDO, MICHAEL",U18 FC Barcelona,4,78,19.50,28.29,110:17
2,2020-21 VALENCIA,3,"VILLAR, RAFA",U18 FC Barcelona,4,76,19.00,34.18,88:56
3,2020-21 VALENCIA,4,"LOEMBA, MARC-ANTOINE",U18 Nanterre 92,4,67,16.75,22.03,121:38
4,2020-21 VALENCIA,5,"RAYNAUD, MAXIME",U18 Nanterre 92,4,65,16.25,18.83,138:04
...,...,...,...,...,...,...,...,...,...
5662,2002-03,89,"GIANNAKIS, DIMITRIS",U18 AEK ATHENS,3,-7,-2.33,-7.57,37:00
5663,2002-03,90,"STRASEVICIUS, SARUNAS",U18 ZALGIRIS KAUNAS,3,-8,-2.67,-10.67,30:00
5664,2002-03,90,"MUBARAK, MOSES",U18 ELAN BEARNAIS PAU ORTHEZ,3,-8,-2.67,-9.14,35:00
5665,2002-03,92,"MAXIMOV, SERGIOS",U18 AEK ATHENS,3,-10,-3.33,-8.16,49:00
5666,2002-03,93,"KULENOVIC, EMIR",U18 UNION OLIMPIJA LJUBLJANA,3,-11,-3.67,-9.57,46:00

In [12]:
dup_index = baseU18.groupby(['player'])['index'].transform(max) == baseU18['index']
base_index = baseU18[dup_index].sort_values(by=['player'])

In [13]:
base_index

,season,rank,player,team,games,index,average,per_40min,minutes
654,2018-19 KAUNAS,4,"ABAD, MAURO",U18 TORRONS VICENS L'HOSPITALET,4,74,18.50,29.37,100:46
3142,2012-13,11,"ABALDE, ALBERTO",IJT CLUB JOVENTUT BADALONA,9,115,12.78,19.82,232:08
5622,2002-03,47,"ABBAD, ROMAIN",U18 ELAN BEARNAIS PAU ORTHEZ,3,9,3.00,4.86,74:00
4542,2009-10,286,"ABIA, LARRY",IJT POWER ELECTRONICS,3,4,1.33,3.73,42:54
2131,2015-16 KAUNAS,67,"ABRAHA, FEKREMARIAM",U18 PORSCHE BASKETBALL ACADEMY LUDWIGSBURG,3,2,0.67,1.95,40:56
...,...,...,...,...,...,...,...,...,...
89,2020-21 VALENCIA,89,"ZULEMIE, NATHAN",U18 Nanterre 92,4,-5,-1.25,-3.02,66:07
4895,2008-09,222,"ZUYKOV, DANYLO",BC KYIV,4,8,2.00,2.64,121:01
3882,2011-12,343,"ZVEREV, NIKITA",IJT BC KHIMKI MOSCOW REGION,3,0,0.00,0.00,10:11
3574,2011-12,39,"ZVIGURS, IVARS",IJT VEF RIGA,4,69,17.25,20.97,131:38
1978,2015-16 BELGRADE,10,"ZYLKA, FERDINAND",U18 ALBA BERLIN,4,85,21.25,30.48,111:33

In [14]:
dup_avg = base_index.groupby(['player'])['average'].transform(max) == base_index['average']
base = base_index[dup_avg].sort_values(by=['player'])

In [15]:
base

,season,rank,player,team,games,index,average,per_40min,minutes
654,2018-19 KAUNAS,4,"ABAD, MAURO",U18 TORRONS VICENS L'HOSPITALET,4,74,18.50,29.37,100:46
3142,2012-13,11,"ABALDE, ALBERTO",IJT CLUB JOVENTUT BADALONA,9,115,12.78,19.82,232:08
5622,2002-03,47,"ABBAD, ROMAIN",U18 ELAN BEARNAIS PAU ORTHEZ,3,9,3.00,4.86,74:00
4542,2009-10,286,"ABIA, LARRY",IJT POWER ELECTRONICS,3,4,1.33,3.73,42:54
2131,2015-16 KAUNAS,67,"ABRAHA, FEKREMARIAM",U18 PORSCHE BASKETBALL ACADEMY LUDWIGSBURG,3,2,0.67,1.95,40:56
...,...,...,...,...,...,...,...,...,...
89,2020-21 VALENCIA,89,"ZULEMIE, NATHAN",U18 Nanterre 92,4,-5,-1.25,-3.02,66:07
4895,2008-09,222,"ZUYKOV, DANYLO",BC KYIV,4,8,2.00,2.64,121:01
3882,2011-12,343,"ZVEREV, NIKITA",IJT BC KHIMKI MOSCOW REGION,3,0,0.00,0.00,10:11
3574,2011-12,39,"ZVIGURS, IVARS",IJT VEF RIGA,4,69,17.25,20.97,131:38
1978,2015-16 BELGRADE,10,"ZYLKA, FERDINAND",U18 ALBA BERLIN,4,85,21.25,30.48,111:33

In [16]:
base.to_csv('baseU18.csv')